version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
      - /workspace/node_modules
    command: sh -c "cd todo-app && yarn start"
    ports:
      - "3000:3000"